version: '3.8'

services:
  job-finder:
    image: ghcr.io/jdubz/job-finder:latest
    container_name: job-finder-production
    restart: unless-stopped

    environment:
      # API Keys - SET THESE IN PORTAINER
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/serviceAccountKey.json

      # Environment Configuration
      - ENVIRONMENT=production

      # Queue Mode - Enable dual-process mode (cron + queue worker)
      - ENABLE_QUEUE_MODE=true

      # Database Configuration - PRODUCTION DATABASES
      - PROFILE_DATABASE_NAME=portfolio
      - STORAGE_DATABASE_NAME=portfolio

      # Config path
      - CONFIG_PATH=/app/config/config.yaml
      - LOG_FILE=/app/logs/scheduler.log

      # Timezone for cron
      - TZ=America/Los_Angeles

    volumes:
      # Mount credentials (REQUIRED)
      - ./credentials:/app/credentials:ro

      # Mount config (optional - use if you want to edit config externally)
      - ./config:/app/config:ro

      # Mount logs for persistence
      - ./logs:/app/logs

      # Mount data for any local file outputs
      - ./data:/app/data

    labels:
      # Watchtower auto-update labels
      - "com.centurylinklabs.watchtower.enable=true"
      - "environment=production"

    networks:
      - job-finder-network

    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s

  # Watchtower for auto-updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower-job-finder-production
    restart: unless-stopped

    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300  # Check every 5 minutes
      - WATCHTOWER_LABEL_ENABLE=true  # Only update containers with watchtower label
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - TZ=America/Los_Angeles

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - job-finder-network

networks:
  job-finder-network:
    driver: bridge
