version: '3.8'

services:
  job-finder:
    image: ghcr.io/jdubz/job-finder:latest
    container_name: job-finder-production
    restart: unless-stopped

    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/serviceAccountKey.json
      - ENVIRONMENT=production
      - ENABLE_QUEUE_MODE=true
      - ENABLE_CLOUD_LOGGING=true
      - PROFILE_DATABASE_NAME=portfolio
      - STORAGE_DATABASE_NAME=portfolio
      - CONFIG_PATH=/app/config/config.yaml
      - LOG_FILE=/app/logs/scheduler.log
      - TZ=America/Los_Angeles

    volumes:
      - /srv/dev-disk-by-uuid-45e47416-96ad-41be-9fc0-582e15241cbd/storage/jobscraper/production/credentials:/app/credentials:ro
      - /srv/dev-disk-by-uuid-45e47416-96ad-41be-9fc0-582e15241cbd/storage/jobscraper/production/config:/app/config:ro
      - /srv/dev-disk-by-uuid-45e47416-96ad-41be-9fc0-582e15241cbd/storage/jobscraper/production/logs:/app/logs
      - /srv/dev-disk-by-uuid-45e47416-96ad-41be-9fc0-582e15241cbd/storage/jobscraper/production/data:/app/data

    labels:
      # Watchtower auto-update labels
      - "com.centurylinklabs.watchtower.enable=true"
      - "environment=production"

    networks:
      - job-finder-network

    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s

  # Watchtower for auto-updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower-job-finder-production
    restart: unless-stopped

    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300  # Check every 5 minutes
      - WATCHTOWER_LABEL_ENABLE=true  # Only update containers with watchtower label
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - TZ=America/Los_Angeles

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - job-finder-network

networks:
  job-finder-network:
    driver: bridge
