# Job Finder Configuration
# Copy this file to config.yaml and customize for your needs

# User Profile - Path to your JSON profile data
# Create a profile using ProfileLoader.create_template() or export from your portfolio
profile:
  # Profile source: "json" or "firestore"
  source: "json"  # Options: "json", "firestore"

  # Path to profile JSON file (used when source is "json")
  profile_path: "data/profile.json"

  # Firestore settings (used when source is "firestore")
  firestore:
    database_name: "portfolio"  # Firestore database name
    user_id: null  # Optional: filter by user ID
    name: "Your Name"  # Your name for the profile
    email: "your.email@example.com"  # Your email for the profile

  # Legacy keyword-based filtering (used if profile_path is not set)
  keywords:
    - python
    - software engineer
    - backend developer

  experience_years: 5

  preferred_locations:
    - remote
    - San Francisco
    - New York

  excluded_keywords:
    - junior
    - intern

# Job Sites to Scrape
sites:
  linkedin:
    enabled: true
    url: "https://www.linkedin.com/jobs/search"

  indeed:
    enabled: true
    url: "https://www.indeed.com"

  # Add more sites as needed

# Scraping Settings
scraping:
  delay_between_requests: 2  # seconds
  max_pages_per_site: 5
  timeout: 30  # seconds

# Output Settings
output:
  format: json  # json, csv, or database
  file_path: data/jobs.json

# AI-Powered Job Matching
ai:
  enabled: true  # Enable AI-powered job analysis and resume intake generation
  provider: "claude"  # Options: "claude", "openai"
  model: "claude-opus-4-20250514"  # Model to use (claude-opus-4-20250514, claude-3-5-sonnet-20241022, gpt-4o, etc.)
  min_match_score: 70  # Minimum match score (0-100) for a job to be included
  generate_intake_data: true  # Generate resume intake data for matched jobs

  # Model-specific settings
  # Each model can have custom maxTokens and temperature
  models:
    # === Claude Models ===
    # Haiku - Fast & cost-effective ($1/$5 per MTok)
    claude-3-5-haiku-20241022:
      max_tokens: 4096
      temperature: 0.3
    claude-3-haiku-20240307:
      max_tokens: 4096
      temperature: 0.3
    # Sonnet - Balanced performance & cost ($3/$15 per MTok)
    claude-3-5-sonnet-20241022:
      max_tokens: 8000
      temperature: 0.3
    claude-3-5-sonnet-20240620:
      max_tokens: 8000
      temperature: 0.3
    claude-3-sonnet-20240229:
      max_tokens: 4096
      temperature: 0.3
    # Opus - Most capable, highest cost ($15/$75 per MTok)
    claude-3-opus-20240229:
      max_tokens: 4096
      temperature: 0.3
    claude-opus-4-20250514:
      max_tokens: 8000
      temperature: 0.3
    # === OpenAI Models ===
    # GPT-4 Turbo ($10/$30 per MTok)
    gpt-4-turbo:
      max_tokens: 4096
      temperature: 0.3
    gpt-4-turbo-2024-04-09:
      max_tokens: 4096
      temperature: 0.3
    # GPT-4o - Latest multimodal ($2.50-5/$10-15 per MTok)
    gpt-4o:
      max_tokens: 4096
      temperature: 0.3
    gpt-4o-2024-11-20:
      max_tokens: 4096
      temperature: 0.3
    gpt-4o-2024-08-06:
      max_tokens: 4096
      temperature: 0.3
    # GPT-4o Mini - Most cost-effective ($0.15/$0.60 per MTok)
    gpt-4o-mini:
      max_tokens: 4096
      temperature: 0.3
    gpt-4o-mini-2024-07-18:
      max_tokens: 4096
      temperature: 0.3
    # Legacy GPT-4 ($30/$60 per MTok)
    gpt-4:
      max_tokens: 8000
      temperature: 0.3
    gpt-4-0613:
      max_tokens: 8000
      temperature: 0.3

  # Fallback settings if model not in models map
  max_tokens: 4096  # Conservative default
  temperature: 0.3

  user_timezone: -8  # User's timezone offset from UTC (Pacific: -8, Mountain: -7, Central: -6, Eastern: -5)
  prefer_large_companies: true  # Prefer large companies over small/startups (+10 for large, -5 for small)

# Filtering
filters:
  min_salary: null
  max_age_days: 7  # only jobs posted in last 7 days
