# Job Finder Configuration - PRODUCTION
# This configuration uses the production Firestore database

# User Profile
profile:
  source: "firestore"

  firestore:
    database_name: "portfolio"  # PRODUCTION database
    user_id: null
    name: "Josh Wentworth"
    email: "Contact@joshwentworth.com"

# Scraping Settings
scraping:
  delay_between_requests: 2  # seconds
  max_pages_per_site: 5
  timeout: 30  # seconds

# Firestore Storage
storage:
  database_name: "portfolio"  # PRODUCTION database for job matches
  collection_name: "job-matches"

# Job Search Settings
search:
  remote_only: true
  max_jobs: 20  # Higher limit for production

# AI-Powered Job Matching
ai:
  enabled: true
  provider: "claude"
  model: "claude-3-haiku-20240307"
  min_match_score: 70
  generate_intake_data: true
  max_tokens: 3000
  temperature: 0.3
  portland_office_bonus: 15  # Bonus points for companies with Portland, OR offices
  user_timezone: -8  # User's timezone offset from UTC (Pacific Time)
  prefer_large_companies: true  # Prefer large companies over small/startups

# Filtering
filters:
  min_salary: null
  max_age_days: 7
