# Job Finder Configuration
# Copy this file to config.yaml and customize for your needs

# User Profile - Path to your JSON profile data
# Create a profile using ProfileLoader.create_template() or export from your portfolio
profile:
  # Path to profile JSON file (leave empty to use legacy keyword-based filtering)
  profile_path: "data/profile.json"

  # Legacy keyword-based filtering (used if profile_path is not set)
  keywords:
    - python
    - software engineer
    - backend developer

  experience_years: 5

  preferred_locations:
    - remote
    - San Francisco
    - New York

  excluded_keywords:
    - junior
    - intern

# Job Sites to Scrape
sites:
  linkedin:
    enabled: true
    url: "https://www.linkedin.com/jobs/search"

  indeed:
    enabled: true
    url: "https://www.indeed.com"

  # Add more sites as needed

# Scraping Settings
scraping:
  delay_between_requests: 2  # seconds
  max_pages_per_site: 5
  timeout: 30  # seconds

# Output Settings
output:
  format: json  # json, csv, or database
  file_path: data/jobs.json

# AI-Powered Job Matching
ai:
  enabled: true  # Enable AI-powered job analysis and resume intake generation
  provider: "claude"  # Options: "claude", "openai"
  model: "claude-3-5-sonnet-20241022"  # Model to use (claude-3-5-sonnet-20241022, gpt-4o, etc.)
  min_match_score: 70  # Minimum match score (0-100) for a job to be included
  generate_intake_data: true  # Generate resume intake data for matched jobs
  max_tokens: 3000  # Maximum tokens for AI responses
  temperature: 0.3  # Temperature for AI responses (0.0-1.0, lower = more consistent)

# Filtering
filters:
  min_salary: null
  max_age_days: 7  # only jobs posted in last 7 days
